### ISSUE TITLE
Rounding errors?

### ISSUE THREAD

**Issue by Alasdairbugs** [slashinfty/yt-frame-timer#12]
Hiya, I moderate for SuperTux speedrunning

I tested this tool with a manual retime using avidemux selection tool and got 

![image](https://github.com/slashinfty/yt-frame-timer/assets/41154567/0380f73b-6122-4d09-9666-dec92530935d)

versus

![image](https://github.com/slashinfty/yt-frame-timer/assets/41154567/6e5dce10-21ff-4c90-aaab-ec1224cca0cd)

using your tool. as you can see, i think the rounding error caused it to be +0.001 s off?

**Comment by slashinfty** [comment]
I wouldn't call it a rounding error when it's rounding, while Avidemux isn't rounding at all (it's truncating).
